//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acMaster
    {
        public int acMasterID { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> propertyID { get; set; }
        public Nullable<int> inspectionID { get; set; }
        public string comments { get; set; }
        public Nullable<int> acType { get; set; }
        public Nullable<int> approximateAge { get; set; }
        public Nullable<int> acDistribution { get; set; }
        public Nullable<int> filterSize { get; set; }
        public Nullable<int> acOperation { get; set; }
        public Nullable<int> overallCondition { get; set; }
    
        public virtual inspectionMaster inspectionMaster { get; set; }
        public virtual OS_AcDistribution OS_AcDistribution { get; set; }
        public virtual OS_AcOperation OS_AcOperation { get; set; }
        public virtual OS_AcType OS_AcType { get; set; }
        public virtual OS_ApproximateAge OS_ApproximateAge { get; set; }
        public virtual OS_Condition OS_Condition { get; set; }
        public virtual OS_FilterSize OS_FilterSize { get; set; }
        public virtual propertyMaster propertyMaster { get; set; }
    }
}
