//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fireplaceMaster
    {
        public int fireplaceMasterID { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> propertyID { get; set; }
        public Nullable<int> inspectionID { get; set; }
        public string comments { get; set; }
        public Nullable<int> fireplaceDamper { get; set; }
        public Nullable<int> woodStove { get; set; }
        public Nullable<int> overallCondition { get; set; }
    
        public virtual inspectionMaster inspectionMaster { get; set; }
        public virtual OS_FireplaceDamper OS_FireplaceDamper { get; set; }
        public virtual OS_WoodStove OS_WoodStove { get; set; }
        public virtual propertyMaster propertyMaster { get; set; }
    }
}
