//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class heatingSystemMaster
    {
        public int heatingSystemID { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> propertyID { get; set; }
        public Nullable<int> inspectionID { get; set; }
        public string comments { get; set; }
        public Nullable<int> heatingSystemType { get; set; }
        public Nullable<int> approximateAge { get; set; }
        public Nullable<int> distributionSystem { get; set; }
        public Nullable<int> fuelAndSource { get; set; }
        public Nullable<int> operation { get; set; }
        public Nullable<System.DateTime> lastServiceDate { get; set; }
        public string serviceBy { get; set; }
        public Nullable<int> asbestos { get; set; }
        public Nullable<int> oilTank { get; set; }
        public Nullable<int> overallCondition { get; set; }
        public Nullable<int> tNPPiping { get; set; }
        public Nullable<int> recommendService { get; set; }
        public Nullable<int> seePage { get; set; }
    
        public virtual inspectionMaster inspectionMaster { get; set; }
        public virtual OS_ApproximateAge OS_ApproximateAge { get; set; }
        public virtual OS_Asbestos OS_Asbestos { get; set; }
        public virtual OS_Condition OS_Condition { get; set; }
        public virtual OS_DistributionSystem OS_DistributionSystem { get; set; }
        public virtual OS_FuelAndSource OS_FuelAndSource { get; set; }
        public virtual OS_HeatingSystemType OS_HeatingSystemType { get; set; }
        public virtual OS_OilTank OS_OilTank { get; set; }
        public virtual OS_Operation OS_Operation { get; set; }
        public virtual OS_RecommendService OS_RecommendService { get; set; }
        public virtual OS_SeePage OS_SeePage { get; set; }
        public virtual OS_TnPPipping OS_TnPPipping { get; set; }
        public virtual propertyMaster propertyMaster { get; set; }
    }
}
