//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeCheckEntities : DbContext
    {
        public HomeCheckEntities()
            : base("name=HomeCheckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<acMaster> acMasters { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<cityMaster> cityMasters { get; set; }
        public virtual DbSet<electricalMaster> electricalMasters { get; set; }
        public virtual DbSet<exteriorMaster> exteriorMasters { get; set; }
        public virtual DbSet<fireplaceMaster> fireplaceMasters { get; set; }
        public virtual DbSet<heatingSystemMaster> heatingSystemMasters { get; set; }
        public virtual DbSet<inspectionMaster> inspectionMasters { get; set; }
        public virtual DbSet<interiorMaster> interiorMasters { get; set; }
        public virtual DbSet<OS_AcDistribution> OS_AcDistribution { get; set; }
        public virtual DbSet<OS_AcOperation> OS_AcOperation { get; set; }
        public virtual DbSet<OS_AcType> OS_AcType { get; set; }
        public virtual DbSet<OS_AdditionalBuildings> OS_AdditionalBuildings { get; set; }
        public virtual DbSet<OS_Alarm> OS_Alarm { get; set; }
        public virtual DbSet<OS_AluminiumWiring> OS_AluminiumWiring { get; set; }
        public virtual DbSet<OS_ApproximateAge> OS_ApproximateAge { get; set; }
        public virtual DbSet<OS_Asbestos> OS_Asbestos { get; set; }
        public virtual DbSet<OS_AtticAccess> OS_AtticAccess { get; set; }
        public virtual DbSet<OS_AtticOpenWire> OS_AtticOpenWire { get; set; }
        public virtual DbSet<OS_AtticVentilation> OS_AtticVentilation { get; set; }
        public virtual DbSet<OS_Balconies> OS_Balconies { get; set; }
        public virtual DbSet<OS_Basement> OS_Basement { get; set; }
        public virtual DbSet<OS_BasementSeepage> OS_BasementSeepage { get; set; }
        public virtual DbSet<OS_buildingType> OS_buildingType { get; set; }
        public virtual DbSet<OS_CeilingFraming> OS_CeilingFraming { get; set; }
        public virtual DbSet<OS_ChimneyComposition> OS_ChimneyComposition { get; set; }
        public virtual DbSet<OS_Condition> OS_Condition { get; set; }
        public virtual DbSet<OS_Decks> OS_Decks { get; set; }
        public virtual DbSet<OS_DistributionSystem> OS_DistributionSystem { get; set; }
        public virtual DbSet<OS_DoorOpeners> OS_DoorOpeners { get; set; }
        public virtual DbSet<OS_Doors> OS_Doors { get; set; }
        public virtual DbSet<OS_DrainVent> OS_DrainVent { get; set; }
        public virtual DbSet<OS_Driveway> OS_Driveway { get; set; }
        public virtual DbSet<OS_DrivewayCondition> OS_DrivewayCondition { get; set; }
        public virtual DbSet<OS_eaves> OS_eaves { get; set; }
        public virtual DbSet<OS_ExteriorPaint> OS_ExteriorPaint { get; set; }
        public virtual DbSet<OS_FilterSize> OS_FilterSize { get; set; }
        public virtual DbSet<OS_FireDoor> OS_FireDoor { get; set; }
        public virtual DbSet<OS_FireplaceDamper> OS_FireplaceDamper { get; set; }
        public virtual DbSet<OS_Flashing> OS_Flashing { get; set; }
        public virtual DbSet<OS_FloorFraming> OS_FloorFraming { get; set; }
        public virtual DbSet<OS_FloorSupport> OS_FloorSupport { get; set; }
        public virtual DbSet<OS_Foundation> OS_Foundation { get; set; }
        public virtual DbSet<OS_FuelAndSource> OS_FuelAndSource { get; set; }
        public virtual DbSet<OS_GarageDoors> OS_GarageDoors { get; set; }
        public virtual DbSet<OS_Grading> OS_Grading { get; set; }
        public virtual DbSet<OS_Ground> OS_Ground { get; set; }
        public virtual DbSet<OS_HeatingSystemType> OS_HeatingSystemType { get; set; }
        public virtual DbSet<OS_HomeStatus> OS_HomeStatus { get; set; }
        public virtual DbSet<OS_HotWaterSystem> OS_HotWaterSystem { get; set; }
        public virtual DbSet<OS_InsulationAttic> OS_InsulationAttic { get; set; }
        public virtual DbSet<OS_InsulationBasement> OS_InsulationBasement { get; set; }
        public virtual DbSet<OS_InsulationWalls> OS_InsulationWalls { get; set; }
        public virtual DbSet<OS_InteriorDoors> OS_InteriorDoors { get; set; }
        public virtual DbSet<OS_InteriorFloors> OS_InteriorFloors { get; set; }
        public virtual DbSet<OS_InteriorWallsCeilings> OS_InteriorWallsCeilings { get; set; }
        public virtual DbSet<OS_InteriorWindows> OS_InteriorWindows { get; set; }
        public virtual DbSet<OS_MainPanelLocation> OS_MainPanelLocation { get; set; }
        public virtual DbSet<OS_MethodOfInspection> OS_MethodOfInspection { get; set; }
        public virtual DbSet<OS_NoOfLayers> OS_NoOfLayers { get; set; }
        public virtual DbSet<OS_OilTank> OS_OilTank { get; set; }
        public virtual DbSet<OS_OpenSpliceBoxes> OS_OpenSpliceBoxes { get; set; }
        public virtual DbSet<OS_Operation> OS_Operation { get; set; }
        public virtual DbSet<OS_OverloadProtection> OS_OverloadProtection { get; set; }
        public virtual DbSet<OS_PanelFeed> OS_PanelFeed { get; set; }
        public virtual DbSet<OS_PanelLabel> OS_PanelLabel { get; set; }
        public virtual DbSet<OS_PresentAtInspection> OS_PresentAtInspection { get; set; }
        public virtual DbSet<OS_RecommendService> OS_RecommendService { get; set; }
        public virtual DbSet<OS_ReversingSafety> OS_ReversingSafety { get; set; }
        public virtual DbSet<OS_RoofDrainage> OS_RoofDrainage { get; set; }
        public virtual DbSet<OS_RoofFraming> OS_RoofFraming { get; set; }
        public virtual DbSet<OS_RoofingMaterial> OS_RoofingMaterial { get; set; }
        public virtual DbSet<OS_SeePage> OS_SeePage { get; set; }
        public virtual DbSet<OS_ServiceEntry> OS_ServiceEntry { get; set; }
        public virtual DbSet<OS_Siding> OS_Siding { get; set; }
        public virtual DbSet<OS_SkyLights> OS_SkyLights { get; set; }
        public virtual DbSet<OS_SmokeDetectors> OS_SmokeDetectors { get; set; }
        public virtual DbSet<OS_soilCondition> OS_soilCondition { get; set; }
        public virtual DbSet<OS_Steps> OS_Steps { get; set; }
        public virtual DbSet<OS_SubPanelLocation> OS_SubPanelLocation { get; set; }
        public virtual DbSet<OS_TarPaper> OS_TarPaper { get; set; }
        public virtual DbSet<OS_Temperature> OS_Temperature { get; set; }
        public virtual DbSet<OS_Termites> OS_Termites { get; set; }
        public virtual DbSet<OS_TnPPipping> OS_TnPPipping { get; set; }
        public virtual DbSet<OS_VaporBarriers> OS_VaporBarriers { get; set; }
        public virtual DbSet<OS_Vegetation> OS_Vegetation { get; set; }
        public virtual DbSet<OS_VoltageRating> OS_VoltageRating { get; set; }
        public virtual DbSet<OS_walks> OS_walks { get; set; }
        public virtual DbSet<OS_WallFraming> OS_WallFraming { get; set; }
        public virtual DbSet<OS_Waste> OS_Waste { get; set; }
        public virtual DbSet<OS_WaterMain> OS_WaterMain { get; set; }
        public virtual DbSet<OS_WaterMainDiameter> OS_WaterMainDiameter { get; set; }
        public virtual DbSet<OS_WaterSupplyPiping> OS_WaterSupplyPiping { get; set; }
        public virtual DbSet<OS_Weather> OS_Weather { get; set; }
        public virtual DbSet<OS_WireType> OS_WireType { get; set; }
        public virtual DbSet<OS_WoodStove> OS_WoodStove { get; set; }
        public virtual DbSet<plumbingMaster> plumbingMasters { get; set; }
        public virtual DbSet<propertyMaster> propertyMasters { get; set; }
        public virtual DbSet<roofMaster> roofMasters { get; set; }
        public virtual DbSet<stateMaster> stateMasters { get; set; }
        public virtual DbSet<statusMaster> statusMasters { get; set; }
        public virtual DbSet<structureMaster> structureMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userMaster> userMasters { get; set; }

    }
}
