//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interiorMaster
    {
        public int interiorMasterID { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> propertyID { get; set; }
        public Nullable<int> inspectionID { get; set; }
        public string comments { get; set; }
        public Nullable<int> interiorWallsCeilings { get; set; }
        public Nullable<int> interiorFloors { get; set; }
        public Nullable<int> interiorWindows { get; set; }
        public Nullable<int> interiorDoors { get; set; }
        public Nullable<int> garageDoors { get; set; }
        public Nullable<int> doorOpeners { get; set; }
        public Nullable<int> reversingSafety { get; set; }
        public Nullable<int> fireDoor { get; set; }
        public Nullable<int> basementSeepage { get; set; }
        public Nullable<int> insulationBasement { get; set; }
        public Nullable<int> insulationWalls { get; set; }
        public Nullable<int> insulationAttic { get; set; }
        public Nullable<int> atticAccess { get; set; }
        public Nullable<int> vaporBarriers { get; set; }
        public Nullable<int> overallCondition { get; set; }
    
        public virtual inspectionMaster inspectionMaster { get; set; }
        public virtual OS_AtticAccess OS_AtticAccess { get; set; }
        public virtual OS_BasementSeepage OS_BasementSeepage { get; set; }
        public virtual OS_Condition OS_Condition { get; set; }
        public virtual OS_DoorOpeners OS_DoorOpeners { get; set; }
        public virtual OS_FireDoor OS_FireDoor { get; set; }
        public virtual OS_GarageDoors OS_GarageDoors { get; set; }
        public virtual OS_InsulationAttic OS_InsulationAttic { get; set; }
        public virtual OS_InsulationBasement OS_InsulationBasement { get; set; }
        public virtual OS_InsulationWalls OS_InsulationWalls { get; set; }
        public virtual OS_InteriorDoors OS_InteriorDoors { get; set; }
        public virtual OS_InteriorFloors OS_InteriorFloors { get; set; }
        public virtual OS_InteriorWallsCeilings OS_InteriorWallsCeilings { get; set; }
        public virtual OS_InteriorWindows OS_InteriorWindows { get; set; }
        public virtual OS_ReversingSafety OS_ReversingSafety { get; set; }
        public virtual OS_VaporBarriers OS_VaporBarriers { get; set; }
        public virtual propertyMaster propertyMaster { get; set; }
    }
}
