//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public propertyMaster()
        {
            this.acMasters = new HashSet<acMaster>();
            this.electricalMasters = new HashSet<electricalMaster>();
            this.exteriorMasters = new HashSet<exteriorMaster>();
            this.fireplaceMasters = new HashSet<fireplaceMaster>();
            this.heatingSystemMasters = new HashSet<heatingSystemMaster>();
            this.interiorMasters = new HashSet<interiorMaster>();
            this.plumbingMasters = new HashSet<plumbingMaster>();
            this.roofMasters = new HashSet<roofMaster>();
            this.structureMasters = new HashSet<structureMaster>();
        }
    
        public int propertyID { get; set; }
        public Nullable<int> buildingType { get; set; }
        public string year { get; set; }
        public Nullable<int> soilConditions { get; set; }
        public Nullable<int> weather { get; set; }
        public Nullable<int> temperature { get; set; }
        public Nullable<int> homeStatus { get; set; }
        public Nullable<int> presentAtInspection { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acMaster> acMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<electricalMaster> electricalMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exteriorMaster> exteriorMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fireplaceMaster> fireplaceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<heatingSystemMaster> heatingSystemMasters { get; set; }
        public virtual inspectionMaster inspectionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interiorMaster> interiorMasters { get; set; }
        public virtual OS_buildingType OS_buildingType { get; set; }
        public virtual OS_HomeStatus OS_HomeStatus { get; set; }
        public virtual OS_PresentAtInspection OS_PresentAtInspection { get; set; }
        public virtual OS_soilCondition OS_soilCondition { get; set; }
        public virtual OS_Temperature OS_Temperature { get; set; }
        public virtual OS_Weather OS_Weather { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plumbingMaster> plumbingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roofMaster> roofMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structureMaster> structureMasters { get; set; }
    }
}
