//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class structureMaster
    {
        public int structureID { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> propertyID { get; set; }
        public Nullable<int> inspectionID { get; set; }
        public Nullable<int> foundation { get; set; }
        public Nullable<int> floorFraming { get; set; }
        public Nullable<int> floorSupport { get; set; }
        public Nullable<int> wallFraming { get; set; }
        public Nullable<int> ceilingFraming { get; set; }
        public Nullable<int> roofFraming { get; set; }
        public Nullable<int> additionalBuildings { get; set; }
        public Nullable<int> overallCondition { get; set; }
        public Nullable<int> termites { get; set; }
        public Nullable<bool> extensiveRange { get; set; }
        public Nullable<int> basement { get; set; }
        public string comments { get; set; }
    
        public virtual inspectionMaster inspectionMaster { get; set; }
        public virtual OS_AdditionalBuildings OS_AdditionalBuildings { get; set; }
        public virtual OS_Basement OS_Basement { get; set; }
        public virtual OS_CeilingFraming OS_CeilingFraming { get; set; }
        public virtual OS_Condition OS_Condition { get; set; }
        public virtual OS_FloorFraming OS_FloorFraming { get; set; }
        public virtual OS_FloorSupport OS_FloorSupport { get; set; }
        public virtual OS_Foundation OS_Foundation { get; set; }
        public virtual OS_RoofFraming OS_RoofFraming { get; set; }
        public virtual OS_Termites OS_Termites { get; set; }
        public virtual OS_WallFraming OS_WallFraming { get; set; }
        public virtual propertyMaster propertyMaster { get; set; }
    }
}
