//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCheck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userMaster
    {
        public int userID { get; set; }
        public string firstName { get; set; }
        public string midInit { get; set; }
        public string lastName { get; set; }
        public string addressLineOne { get; set; }
        public string addressLineTwo { get; set; }
        public Nullable<int> addressCity { get; set; }
        public Nullable<int> addressState { get; set; }
        public string addressZip { get; set; }
    
        public virtual cityMaster cityMaster { get; set; }
        public virtual stateMaster stateMaster { get; set; }
    }
}
